### ISSUE TITLE
关于历史记录、多会话管理思路

### ISSUE THREAD

**Issue by Jakentop** [TinyChatZ/tiny-chat-app#19]
一直以来我一直在想如何设计历史记录和多会话管理，我希望他可以不局限于一个应用内部。历史记录多会话管理在底层逻辑上和OpenAI如出一辙，但是在展现形式上我想利用Electron在桌面上的优势……

TinyChat目前有两种形态，一种是缩略图标模式，另一种就是展开的对话界面。TinyChat的初衷是尽可能保持简单的，所以我想把会话选择放在缩略图的状态下完成：当你需要查看某一个会话时把鼠标悬停在图标上就会展示最近的会话列表。此时你可以选择一个历史会话来打开它，关注并继续上次会话。或者你也可以直接点击图标，这就会创建一个新的会话。

在历史记录中，有部分功能会在 #14 完成，由于ChatGPT是一个具有上下文推理能力的生成模型，因此除了展示对话上下文外，还需要可以对对话上下文进行编辑，以更好的完成建议

**Comment by Jakentop** [comment]
到目前为止我们完成了一些基础的功能，以下是历史记录和多会话管理优化的建议：

- [ ] 会话自动命名（首次创建的会话，自动命名）
- [ ] 会话选择逻辑优化（放大模式下直接在顶部标题出弹出一个下拉框）
- [ ] 支持修改会话保存的目录位置（方便用于多端同步，可以把会话位置放在同步文件夹下）
- [ ] 会话状态显示（支持显示会话状态：未激活|生成中|就绪|错误）暂时打算用不同颜色的原点来展示会话的状态
- [ ] 设置优化（添加会话设置、ChatGPT中设置开关允许是否使用代理）

**Comment by 995414558** [comment]
![image](https://github.com/TinyChatZ/tiny-chat-app/assets/66954815/e53b14a8-853e-46e6-b11a-e655ccd34c6e)
图标没有改动，与界面UI不匹配

**Comment by Jakentop** [comment]
1.1.0-beta中发现下述需要修复的bug：

- [ ] 缩略模式下，鼠标悬停后快速移开可能导致弹出层不会自动关闭
- [ ] 窗口拖拽，如果是从文字上开始的，可能会失效，导致拖拽困难

**Comment by Jakentop** [comment]
1.1.0-beta中需要优化的tips：

- [ ] 设置界面支持缩略模式下和展开模式下打开对话框行为（单击还是放置延迟）
- [ ] 自动下拉逻辑优化，一旦当前界面开始生成且当前位于底部时就开始往下拖拽，在此期间如果用户修改了位置则取消自动下拉
