### ISSUE TITLE
滚动条拉到底，顶部图标显示不全

### ISSUE THREAD

**Issue by 995414558** [TinyChatZ/tiny-chat-app#30]
<img width="417" alt="6aa6d9a895a633c9489aea371d2cf58" src="https://github.com/TinyChatZ/tiny-chat-app/assets/66954815/78f267f6-33b3-44f3-88a9-3217e934c021">

正常显示如下：
<img width="303" alt="f3294b5ad58e65e5e548d835cc23522" src="https://github.com/TinyChatZ/tiny-chat-app/assets/66954815/3c225dfc-b919-4837-98af-cdd5f77c150a">

**Comment by Jakentop** [comment]
duplicate #31
