### ISSUE TITLE
对话框右下角小图标显示问题

### ISSUE THREAD

**Issue by 995414558** [TinyChatZ/tiny-chat-app#32]
![image](https://github.com/TinyChatZ/tiny-chat-app/assets/66954815/4863dcd5-67c4-4aa9-bb18-93d66a8f5e52)
如图，红色箭头为光标所在区域，光标所在对话栏显示了右下角操作小图标。
预期结果：只会显示光标所在对话区域的右下角操作小图标。
实际结果：如图

**Comment by Jakentop** [comment]
fixed-it
