### ISSUE TITLE
上传头像显示问题与连续上传头像不刷新问题

### ISSUE THREAD

**Issue by 995414558** [TinyChatZ/tiny-chat-app#35]
![image](https://github.com/TinyChatZ/tiny-chat-app/assets/66954815/15511cb8-97fc-465c-b61f-d4fa18e87af1)
![image](https://github.com/TinyChatZ/tiny-chat-app/assets/66954815/8816ce26-4fbc-42f3-855f-c2e5bdd55f8e)
上传的头像显示不一致
![7a28a290a02b5f3aef7eca1d1e24d4c](https://github.com/TinyChatZ/tiny-chat-app/assets/66954815/6866cf32-8193-4725-a13f-6f708ac6b27a)
![de3b3c3f24ac5c8d2b8ba462fe5836f](https://github.com/TinyChatZ/tiny-chat-app/assets/66954815/87268d13-d4b0-4c7e-9096-f63be87f63e6)
上传头像还出现了，若连续上传头像，则头像不刷新，需要重新打开设置页面才能看到更换后的头像

**Comment by Jakentop** [comment]
我一会儿修复下，这有点麻烦，确实重新上传后不会刷新
